{% set name = "rabbitpy" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rabbitpy-{{ version }}.tar.gz
  sha256: e4e26019164b1cb9e37f5f9a6ce0367c0b3b81d572806158c43871d2d24d0305

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pamqp >=2,<3

test:
  imports:
    - rabbitpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rabbitpy.readthedocs.io
  summary: A pure python, thread-safe, minimalistic and pythonic RabbitMQ client library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
